# Generated by Django 5.0.4 on 2024-05-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('habitat', models.TextField(blank=True, max_length=200)),
                ('requirements', models.TextField(blank=True)),
                ('food', models.TextField(blank=True)),
                ('compatibility', models.JSONField(blank=True)),
                ('photos_count', models.IntegerField()),
            ],
        ),
    ]
