# Generated by Django 5.0.4 on 2024-05-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('habitat', models.TextField()),
                ('requirements', models.TextField()),
                ('food', models.TextField()),
                ('compatibility', models.JSONField(blank=True, default=list, null=True)),
                ('photos_count', models.IntegerField()),
                ('image_paths', models.JSONField()),
            ],
            options={
                'db_table': 'fishes',
            },
        ),
    ]
