# Generated by Django 5.0.4 on 2024-05-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('habitat', models.TextField()),
                ('requirements', models.TextField()),
                ('food', models.TextField()),
                ('compatibility', models.JSONField(default=list)),
                ('photos_count', models.IntegerField()),
                ('image_paths', models.JSONField(default=list)),
            ],
        ),
    ]
