# Generated by Django 5.0.4 on 2024-05-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_web_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishes',
            name='compatibility',
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='fishes',
            name='description',
            field=models.TextField(),
        ),
    ]
